<a href="https://colab.research.google.com/github/pavanarya/AI-ML/blob/main/ML/3.%20FeatureEngineering/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
%matplotlib inline

In [2]:
data = {'EmployeeId':[101,102,103,104,105],
        'Gender':['M','F','M','F','M'],
        'Programminglanguage':['C#','Java','Html','C#','Java']}

df = pd.DataFrame(data)
df

EmployeeId Gender Programminglanguage
0         101      M                  C#
1         102      F                Java
2         103      M                Html
3         104      F                  C#
4         105      M                Java

In [4]:
#Select categorical features
categorical_columns = [col for col in df.columns if df[col].dtype == 'object']
categorical_columns

['Gender', 'Programminglanguage']

In [8]:
encoder = OneHotEncoder(handle_unknown='ignore',sparse_output=False)
encoder.fit(df[categorical_columns])
aa = encoder.transform(df[categorical_columns])
print(aa)

[[0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]]


In [9]:
one_hot_df = pd.DataFrame(aa,columns=encoder.get_feature_names_out())
one_hot_df

Gender_F  Gender_M  Programminglanguage_C#  Programminglanguage_Html  \
0       0.0       1.0                     1.0                       0.0   
1       1.0       0.0                     0.0                       0.0   
2       0.0       1.0                     0.0                       1.0   
3       1.0       0.0                     1.0                       0.0   
4       0.0       1.0                     0.0                       0.0   

   Programminglanguage_Java  
0                       0.0  
1                       1.0  
2                       0.0  
3                       0.0  
4                       1.0

Distance algorithms like KNN, K-means, and SVM are most affected by the range of features. This is because behind the scenes they are using distances between data points to determine their similarity.

For example, let’s say we have data containing high school CGPA scores of students (ranging from 0 to 5) and their future incomes (in thousands Rupees):

![](https://www.googleapis.com/download/storage/v1/b/kaggle-forum-message-attachments/o/inbox%2F10796501%2F6232a66d1b134e67ee3fe863134cac2a%2Fknn_ex.png?generation=1659434743284589&alt=media)

Since both the features have different scales, there is a chance that higher weightage is given to features with higher magnitude. This will impact the performance of the machine learning algorithm and obviously, we do not want our algorithm to be biassed towards one feature.

Therefore, we scale our data before employing a distance based algorithm so that all the features contribute equally to the result.

![](https://www.googleapis.com/download/storage/v1/b/kaggle-forum-message-attachments/o/inbox%2F10796501%2Fb5594af860d750372deef1197f6c41e6%2Fknn_ex_scaled.png?generation=1659434795601561&alt=media)


The effect of scaling is conspicuous when we compare the Euclidean distance between data points for students A and B, and between B and C, before and after scaling as shown below:
- Distance AB before scaling
 ![](https://www.googleapis.com/download/storage/v1/b/kaggle-forum-message-attachments/o/inbox%2F10796501%2F04ad27a7d013bac5cee1c45885017d58%2Feq1.png?generation=1659434922014436&alt=media)
- Distance BC before scaling
![](https://www.googleapis.com/download/storage/v1/b/kaggle-forum-message-attachments/o/inbox%2F10796501%2F7ed34a57eb03e59857194c022634db38%2Feq2.png?generation=1659435086948287&alt=media)
- Distance AB after scaling
![](https://www.googleapis.com/download/storage/v1/b/kaggle-forum-message-attachments/o/inbox%2F10796501%2Fda750c41469beada65569cb38fd1e8d3%2Feq3.png?generation=1659435103794447&alt=media)
- Distance BC after scaling
![](https://www.googleapis.com/download/storage/v1/b/kaggle-forum-message-attachments/o/inbox%2F10796501%2F1a6a552985bb755a9be29c93d2248ea1%2Feq4.png?generation=1659435115887394&alt=media)

Scaling has brought both the features into the picture and the distances are now more comparable than they were before we applied scaling.